# Generated by Django 5.0.2 on 2024-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('summary', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=400)),
                ('skills', models.CharField(max_length=800)),
                ('university', models.TextField(max_length=520)),
                ('previous_work', models.TextField(max_length=2000)),
            ],
        ),
    ]
